### ISSUE TITLE
Recette de gaufres

### ISSUE THREAD

**Issue by bobmaerten** [sogilis/sogifood#5]
Bonjour j'ai de la levure fraiche et je me disais, hummm... il doit bien y avoir une recette de gaufres ici. QUE NENNI ! Uniquement des prototypes. 😭 

Donc voila, si vous pouviez déposer une petite recettes que j'implémente ça ce weekend, ce serait super gentil. Merci !

**Comment by eunomie** [comment]
Oups :-)

**Comment by eunomie** [comment]
@MoussSS en rajoute une très bientôt

**Comment by MoussSS** [comment]
Done!

2017-02-02 16:52 GMT+01:00 Yves Brissaud <notifications@github.com>:

**Comment by bobmaerten** [comment]
Merciiiiiiiii !!!!
